[profile.default]
src = "contracts"
out = "out"
libs = ["lib", "node_modules"]
via_ir = true
optimizer = true
optimizer_runs = 200

[profile.ci]
via_ir = false

[profile.ci.fuzz]
runs = 1024
max_test_rejects = 500

[profile.ci.invariant]
runs = 128
depth = 64

[profile.deep]
via_ir = false

[profile.deep.fuzz]
runs = 10000
max_test_rejects = 1000

[profile.deep.invariant]
runs = 256
depth = 128

[fuzz]
runs = 256
max_test_rejects = 100

[invariant]
runs = 64
depth = 32
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
